print("Second python hello program")

# print("Second python hello program")
print(2 + 2)
print(2 - 2)
print(2 * 2)
print(2 / 2)
print("RUMA", 123, "ghosh", "suuny")
print("RUMA", 123, "ghosh", "suuny")
print("RUMA", 123, "ghosh", "suuny")
print("RUMA", 123, "ghosh", "suuny",sep='_')
print("RUMA", 123, "ghosh", "suuny",sep='*')
print("RUMA", 123, "ghosh", "suuny",sep='*',end="__")
print("RUMA", 123, "ghosh", "suuny",sep='*',end="    ")
